
spring:
  config:
    activate:
      on-profile: "default"

build:
  version: "3.0"

accounts:
  message: "Welcome to Gbadegesin Accounts related APIs"
  contactDetails:
    name: "Idris Gbadegesin Adelabu - Developer"
    email: "idrisadelabu@gmail.com"
  onCallSupport:
    - (123) 456-7890
    - (234) 567-8901