
spring:
  config:
    activate:
      on-profile: "default"

build:
  version: "3.0"

cards:
  message: "Welcome to Gbadegesin Cards related APIs"
  contactDetails:
    name: "Diisu Adelabu - QA Lead"
    email: "diisuadelabu@gmail.com"
  onCallSupport:
    - (803) 012-0186
    - (803) 034-0181