
spring:
  config:
    activate:
      on-profile: "default"

build:
  version: "3.0"

loans:
  message: "Welcome to Gbadegesin Loans related APIs"
  contactDetails:
    name: "Idris Gbadegesin Adelabu - Developer"
    email: "idrisadelabu@gmail.com"
  onCallSupport:
    - (123) 456-7890
    - (234) 567-8901